testB = true
testI = -42
testF = 1.23
testS = "foobar"
testA = [   "abacaba", "foo", 'bar'    ]
testNE = [ "nonEmpty" ]
testNET = [ {a = 1} ]

testEven = 6
# testEven = 5

testN = "newtype"
# testStatus = "username"

testC = "Light"
# testC = "Dark"
# testC = "HighContrast"

# either.Left = 3
either.Right = "Right"

either = 3.5
# Also works!
# either = "fo  o"

intset = [1, 1]

payloads =
    [ { name = "foo", payload = 42 }
    , { name = "bar", payload = 69 }
    ]

testPair = { pNum = 11, pName = "eleven" }

[testTriple]
    tNum = 11
    tName = "eleven"
    isFav = true

[testX]
  inside = "xxx"

# [testY]
#   inside = "yyy"

[[user]]
name = "Foo"
age = 42

[[user]]
name = "Bar"
age = 777

[testStatus]
username = "username"
password = "password"

[colours]
yellow = "#FFFF00"
red    = { red = 255, green = 0, blue = 0 }
pink   = "#FFC0CB"

[mapList]
  [[mapList.k]]
    val = "a"

  [[mapList.k]]
    val = "b"