testB = true
testI = -42
testF = 1.23
testS = "foobar"
testA = [   "abacaba", "foo", 'bar'    ]
testN = "newtype"
# testStatus = "username"

testC = "Light"
# testC = "Dark"
# testC = "HighContrast"

# either.Left = 3
either.Right = "Right"

either = 3.5
# Also works!
# either = "fo  o"

payloads =
    [ { name = "foo", payload = 42 }
    , { name = "bar", payload = 69 }
    ]

[testX]
  inside = "xxx"

# [testY]
#   inside = "yyy"

[[user]]
name = "Foo"
age = 42

[[user]]
name = "Bar"
age = 777

[testStatus]
username = "username"
password = "password"

[colours]
yellow = "#FFFF00"
red    = { red = 255, green = 0, blue = 0 }
pink   = "#FFC0CB"
