a = true
list = ["one", 2, 'two']

[table.name.2]
  2Inner = +42

[table.name.1]
  listInner."google.com" = [true, false]
  aInner = -1

  [table.name.1.1]
    listInner = [true, false]
    aInner = 1

  [table.name.1.2]
    Inner1.2 = 42

[a.b.c.d]